title: "Sequence Learning"
email: korbinian.riedhammer@fh-rosenheim.de
description: "Materials for Sequence Learning (graduate level)"
baseurl: ""
url: "https://sikoried.github.io/sequence-learning/"
exclude: ["LICENSE", "Remarks.md", "examples"]
github_username: ["sikoried"]

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
